name: Publish mf2react (OIDC)

on:
  push:
    branches: [main]
    paths:
      - "mf2react/**"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: publish-mf2react-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mf2react

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect version change
        id: ver
        shell: bash
        run: |
          set -euo pipefail
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            BEFORE="HEAD^"
          else
            BEFORE="HEAD"
          fi

          BEFORE_VER=$(git show "$BEFORE:mf2react/package.json" | jq -r .version 2>/dev/null || echo "")
          NOW_VER=$(jq -r .version package.json)

          if [ -n "$NOW_VER" ] && [ "$BEFORE_VER" != "$NOW_VER" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Node
        if: steps.ver.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install
        if: steps.ver.outputs.changed == 'true'
        run: npm ci

      - name: Build
        if: steps.ver.outputs.changed == 'true'
        run: npm run build

      - name: Publish to npm
        if: steps.ver.outputs.changed == 'true'
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - name: Skip (no version change)
        if: steps.ver.outputs.changed != 'true'
        run: echo "No version bump in mf2react/package.json — skipping publish."
